name: Angular CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Using a recent LTS version
        cache: 'npm' # Enable caching for npm
        cache-dependency-path: lightboard/package-lock.json # Specify path to package-lock.json

    - name: Install dependencies
      working-directory: ./lightboard # Set working directory for this step
      run: npm ci # Use npm ci for faster, more reliable CI builds

    - name: Set CHROME_BIN for Karma
      run: |
        cd lightboard
        export CHROME_BIN=$(node -p -e "require('puppeteer').executablePath()")
        echo "CHROME_BIN=${CHROME_BIN}" >> $GITHUB_ENV

    - name: Run ESLint
      working-directory: ./lightboard
      run: npm run lint

    - name: Run tests
      run: |
        cd lightboard
        npm test -- --no-watch --no-progress --browsers=ChromeHeadlessNoSandbox
      env:
        CHROME_BIN: ${{ env.CHROME_BIN }}

  test_go_server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Updated Go version
          cache: true        # Enable caching for Go modules

      - name: Test Go server
        working-directory: ./server
        run: go test ./...
